export interface Residency {
	slug: string;
	name: string;
	year: string;
	country: string;
	desc: string;
	images: string[];
	video: string;
}

export const residencies: Residency[] = [
		{ slug: 'argya-dhyaksa', name: 'Argya Dhyaksa', year: '2020', country: 'Indonesia', desc: 'Argya Dhyaksa Nindita has an interest in beauty in ugliness and silliness. Most of his ceramic forms are rough, ugly, chaotically imperfect — wabi sabi. With the idea of wabi sabi in mind, we may learn a great satisfaction in a humble moment. He uses the pinch technique for personal touch on his ceramics. "Sacred Admirer" is a ceramic work Argya made while in residence at Tentacles Gallery.', images: ['round-frame.png', 'IMG_8604-2-scaled.jpg', 'IMG_7672-scaled.jpg', 'IMG_8475-scaled.jpg', 'IMG_8151-scaled.jpg', 'IMG_7380-scaled.jpg', 'IMG_8611-2-scaled.jpg', 'IMG_8614-2-scaled.jpg', 'IMG_8615-2-scaled.jpg', 'IMG_8616-2-scaled.jpg', 'IMG_8617-2-scaled.jpg', 'IMG_8621-2-scaled.jpg', 'IMG_8627-2-scaled.jpg'], video: 'cZAUncKgT4Q' },
		{ slug: 'ramesh-ramakrishnah', name: 'Ramesh Ramakrishnah', year: '2019', country: 'Mauritius', desc: 'Ramesh Ramakrishnan (RR) is a photographer, artist and marketer with over three decades of corporate experience in marketing, strategy and general management. Returning to academics in 2018, he graduated with an MA in Asian Art History from Goldsmiths University of London, studying at LaSalle College Singapore. In Tentacles he is working on exploring the changing culture of Bangkok.', images: ['65010206_2177247269233603_7791109973894758400_n-3.jpg', '68776429_436815583847401_5432537629713235968_n.jpg'], video: 'Dw2TW7Flbbk' },
		{ slug: 'li-zhiyong', name: 'Li Zhiyong', year: '2019', country: 'China', desc: 'Li Zhiyong, born in Lufeng, Guangdong, currently lives and works in Guangzhou. He graduated from the Oil Painting Department of the Guangzhou Academy of Fine Arts. As someone who once suffered from insomnia, by combing through physical memories, Zhiyong surmises that insomnia is related to a certain tension.', images: ['mmexport1559127315653-9.jpg', '62840716_2283841451863873_1024527060770488320_o-copy-14.jpg', 'IMG_6645-1.jpg', 'IMG_5470-2-scaled.jpg', 'IMG_5275-2-scaled.jpg', 'IMG_5326-2-scaled.jpg'], video: 'SqC2juMJpgA' },
		{ slug: 'yusuke-shibata', name: 'Yusuke Shibata', year: '2019', country: 'Japan', desc: 'Yusuke Shibata, born in 1980 in Fukuoka, Japan, currently lives and works in Tokyo. He graduated from Musashino Art University in painting and obtained an MFA in Printmaking. The aim of his project is to build the network of video artists in Asia, researching video art history in Asia and how it has influenced today\'s artists.', images: ['66050882_880332782328139_3527803587662970880_n.jpg', '23C40FB4-7096-487B-8E3C-2C78B2746819-4-3.jpg', 'IMG_6427-2-scaled.jpg', 'IMG_6507-2-scaled.jpg', 'IMG_6630.jpg', 'IMG_6272-scaled.jpg', 'IMG_6628.jpg', 'IMG_6633.jpg'], video: 'm30ZPUmrCxQ' },
		{ slug: 'ge-yulu', name: 'Ge Yulu', year: '2019', country: 'China', desc: 'Ge Yulu was born at Wuhan, Hubei. He did his undergraduate in Media Art at Hubei Institute of Fine Arts and postgraduate in experimental art at Central Academy of Fine Arts. He explored the surrounding neighborhood area and was interested in the relationship between people and the artwork in their houses.', images: ['ยูลู่.jpg', 'Yulu-cover-copy.jpg', '68714219_721305961663839_8334826638562820096_n.jpg'], video: 'SqC2juMJpgA' },
		{ slug: 'magdalena-correa', name: 'Magdalena Correa', year: '2019', country: 'Colombia', desc: 'This residency is kindly supported by the Spanish Embassy in Bangkok. During the months of September 2019, the Chilean artist who has lived in Spain for more than 23 years came to Thailand to portray Bangkok from another perspective. She explores the relationship between humans and the territories they inhabit, using photography and video art.', images: ['FOTO-CABRITO.jpg', 'spain2.jpg', '000038.jpeg', '000003.jpeg', '000005.jpeg', '3a0a0b85-fdb9-4547-be09-07cdc7fc0be4-2.jpg', 'eafdb60c-a2cd-4ec5-a91f-b7057953c1b6-2.jpg', '954a5635-af58-42b9-88e9-a6d257b199ba-2.jpg', '71330665-cfd3-4933-b4e3-095e756ed160-3.jpg', '072cd127-9d85-494f-8304-788f41fb12d7-2.jpg'], video: 'yRWQYZMcJuY' },
		{ slug: 'kai-altmann', name: 'Kai Altmann', year: '2019', country: 'USA', desc: 'Kai Altmann (aka Hitashya) is a globally nomadic artist who makes work in conceptually soft-branded "teams" or series which she treats as palettes, identities and states of mind. The identity she worked on in Bangkok is Soft Mobility, for which she sourced materials from art stores, street markets, Alibaba and local markets. She is here thanks to funding from the Asian Cultural Council in New York.', images: ['68651630_487348582062404_2058534467277946880_n-copy.png', '72919622_2373831722864845_4228172282440187904_n.jpg', 'tumblr_inline_q0lht8ic3x1qbtion_1280.jpg', 'tumblr_inline_q0lgh6kJln1qbtion_1280.jpg', 'tumblr_inline_ps4uxe0KIa1qbtion_1280.jpg', 'tumblr_inline_q079x3Mgtx1qbtion_1280.jpg', 'tumblr_inline_q079whnA8y1qbtion_1280.jpg', 'tumblr_inline_q0libstrvQ1qbtion_1280.jpg', 'tumblr_inline_q0lhvuk3y51qbtion_1280.jpg'], video: '' },
		{ slug: 'ip-wai-lung', name: 'Ip Wai Lung', year: '2019', country: 'Hong Kong', desc: 'Ip Wai Lung was born in the Guangdong Province, China, and is an artist residing in Hong Kong. In 1996, he moved to Hong Kong with his mother to reunite with his father right before the handover. His artwork explores social issues, taboos, and identities in a spontaneous and humorous fashion. He believes in the power of public art.', images: ['Untitled-1.jpg', '710C35DE-6257-46A3-8EBE-59F8B6A6CC49.jpeg', 'IMG_0150.jpg', 'IMG_0182.jpg', 'AM8B9919-2-scaled.jpg', 'AM8B9911-2-scaled.jpg', 'AM8B9981-2-scaled.jpg', 'AM8B9984-2-scaled.jpg'], video: '' },
		{ slug: 'gemini-kim', name: 'Gemini Kim', year: '2019', country: 'South Korea / USA', desc: 'Growing up in Korean society with fear of war and militant culture, and as a son of a Korean War refugee, post-war and post-colonial became the main interest of his artwork. In Tentacles, he planned \'The Art of Luxurious Living: In Tentacles Hotel\' — designing \'luxury\' tactics in daily life without cost.', images: ['Kim-scaled.png', 'DSC_0012-scaled.jpg', 'DSC_0011-scaled.jpg', 'DSC_0010-scaled.jpg', '81625893_475903819986241_4402630765922222080_n-scaled.jpg', 'DSC_0021-scaled.jpg', 'DSC_0029-scaled.jpg', 'DSC_0051-scaled.jpg', 'DSC_0056-scaled.jpg', 'DSC_0049-scaled.jpg', 'DSC_0057-scaled.jpg'], video: '' },
		{ slug: 'scott-anderson', name: 'Scott Anderson', year: '2019', country: 'New Zealand', desc: 'Scott\'s practice is an ongoing investigation within the expanded field of painting. His work considers place/non-place and transition/flux within urban environments, and how cultural identities influence one\'s understanding of place. \'18 Minute Walk\' is an installation work inspired by Scott\'s daily experience of getting a coffee.', images: ['26961959_114631926015939_5030924745817707749_o.png', 'IMG_8156-scaled.jpg', '87173726_2484780585103291_7575464184268193792_o.jpg', 'IMG_8389-scaled.jpg', 'IMG_8391-scaled.jpg', 'IMG_8396-scaled.jpg', 'IMG_8400-scaled.jpg', 'IMG_8406-scaled.jpg'], video: 'Gw_RLD706AA' },
		{ slug: 'jane-cheng', name: 'Jane Q Cheng', year: '2018', country: 'Singapore', desc: 'Jane Q Cheng is an artist living in Vancouver, where she received her BFA from Emily Carr University of Art and Design, with a major in illustration.', images: [], video: '' },
		{ slug: 'yosefa-muhammad', name: 'Yosefa Aulia & Muhammad Vilhamy', year: '2016', country: 'Indonesia', desc: 'ไกลตา ไกลใจ (Out of Sight, Out of Mind) is an art project carried out by Indonesian duo artists, Muhammad Vilhamy and Yosefa Aulia, in a residency program held by Tentacles x Yet Space, Bangkok. The project is based on the idea of creating a single moment in which photography became the most appropriate medium to achieve a moment that connects the time, place, and people around the neighborhood.', images: ['IMGP8553-scaled.jpg', 'IMGP8619-scaled.jpg', 'IMGP8618-scaled.jpg', 'IMGP8577-scaled.jpg', 'IMGP8578-scaled.jpg', 'IMGP8654-scaled.jpg', 'IMGP8611-scaled.jpg', 'IMGP8655-scaled.jpg', 'IMGP8599-scaled.jpg', 'IMGP8657-scaled.jpg', 'IMGP8598-scaled.jpg', 'IMGP8660-scaled.jpg', 'IMGP8597-scaled.jpg', 'IMGP8636-scaled.jpg', 'IMGP8573-scaled.jpg'], video: '-_PHexE5TTs' },
		{ slug: 'kong-dara', name: 'Kong Dara', year: '2015', country: 'Cambodia', desc: 'During his residency period, Dara continued his research on the lives of LGBT people, which has been a recurring theme in his recent works, while observing passengers on the public van between Rathchaburi and Bangkok and on the BTS. On the most basic level his work deals with the lack of openness between people in contemporary society.', images: ['IMG_7508-scaled.jpg', 'IMG_7560-scaled.jpg', 'IMG_7578-scaled.jpg', 'IMG_7577-scaled.jpg', 'IMG_7565-scaled.jpg', 'IMGP6698-scaled.jpg', 'IMGP6668-scaled.jpg', 'IMG_7566-scaled.jpg', 'IMGP6650-scaled.jpg'], video: '' },
		{ slug: 'amy-wang', name: 'Amy Wang / Jhong ChengShiu', year: '2015', country: 'Taiwan', desc: 'My name is Amy. I\'m from Taiwan. I\'m studying animation at Taipei National University of Arts. I make animations, and also have some works, like comics and illustrations. My works mostly talk about relationship and human being — some kind of indirect expression. I love the rich emotion situations.', images: ['IMGP5769.jpg', 'IMGP5773.jpg', 'IMGP5777.jpg', 'IMGP5780.jpg', 'IMGP5783.jpg', 'IMGP5784.jpg', 'IMGP5787.jpg', 'IMGP5740.jpg', 'IMGP5748.jpg'], video: '' },
		{ slug: 'david-delgado', name: 'David Delgado', year: '2015', country: 'Colombia', desc: 'Nothing interests me as much as Grace. I truly believe Grace is the essence of all of the Arts. I love the delicacy and at the same time I feel attracted by the trash culture. My only quest is to do a full, complete work, from honesty and innocence.', images: ['1375027_10151651352967131_49888493_n.jpg', 'IMGP0504.jpg', 'IMGP0518.jpg', 'IMGP0508.jpg', 'IMGP0545.jpg', 'IMGP0581.jpg'], video: '' },
		{ slug: 'pohan-chang', name: 'Pohan Chang', year: '2015', country: 'Taiwan', desc: 'Pohan, born in 1989 Chiayi, Taiwan, graduated from the department of Engineering. Instead of being an engineer like her classmates, she wants to face the reality. She is interested in participatory art and experimenting with space, to investigate the possibility of space.', images: ['pohan.jpg'], video: 'Oin-GOnYi7A' },

		{ slug: 'abijan-gupta', name: 'Abijan Gupta', year: '2017', country: 'India', desc: 'Indian artist exploring the intersections of technology, craft, and cultural heritage. During his 2017 residency, Gupta revived traditional Indian craft techniques through contemporary digital processes.', images: ['abijan-gupta-1.jpg'], video: '' },
		{ slug: 'ajoon-martia-saputri', name: 'Ajoon Martia Saputri', year: '2017', country: 'Indonesia', desc: 'Indonesian artist exploring gender, myth, and post-colonial identity through drawing and installation. During her 2017 residency at TENTACLES, Saputri created intricate works weaving together Javanese folklore, feminist critique, and personal narrative.', images: ['Ajoon-pdf.jpg', 'Ajoon-pdf-1.jpg'], video: '' },
		{ slug: 'cyril-shanna', name: 'Cyril & Shanna', year: '2017', country: 'International', desc: 'Collaborative duo working at the intersection of performance, sound, and visual art. During their 2017 residency, their practice explored the politics of listening, the body as instrument, and the spaces between language and music.', images: ['Cyrill-shanna-pdf.jpg', 'Shanna-Cyril-@-WiFri-LoRes.jpg'], video: '' },
		{ slug: 'din-chan', name: 'Din Chan', year: '2017', country: 'Thailand', desc: 'Bangkok-based artist whose installation practice explores social narratives and public space. During his 2017 residency, Chan created immersive environments using everyday materials.', images: ['Dude-chung-pdf.jpg'], video: '' },
		{ slug: 'flounder-lee', name: 'Flounder Lee', year: '2017', country: 'USA', desc: 'American photographer and educator examining landscape, infrastructure, and environmental change. During his 2017 residency, Lee created large-format photographs documenting the Anthropocene.', images: ['Flounder-pdf.jpg'], video: '' },
		{ slug: 'garima-gupta', name: 'Garima Gupta', year: '2017', country: 'India', desc: 'Indian artist whose work spans printmaking, papermaking, and participatory art processes. During her 2017 residency, Gupta’s practice was rooted in material experimentation and community engagement.', images: ['garima.png'], video: '' },
		{ slug: 'hernan-salvo', name: 'Hernan Salvo', year: '2017', country: 'Mexico', desc: 'Mexican artist exploring ritual, textile, and the poetics of everyday materials. During his 2017 residency, Salvo created woven installations and sculptural works drawing on pre-Columbian textile traditions.', images: ['Hernan-Salvo-pdf.jpg'], video: '' },
		{ slug: 'hiromi-tsuha', name: 'Hiromi Tsuha', year: '2017', country: 'Japan (Okinawa)', desc: 'Japanese artist from Okinawa, working with installation, video, and performance exploring island identity. During her 2017 residency, Tsuha’s work addressed Okinawa’s contested history and the resilience of Ryukyuan culture.', images: ['Hiromi-Tsuha-pdf.jpg', 'hiromi-tsuha-1.jpg', 'hiromi-tsuha-2.jpg', 'hiromi-tsuha-3.jpg'], video: '' },
		{ slug: 'justin-loke', name: 'Justin Loke', year: '2017', country: 'Singapore', desc: 'Singaporean painter and installation artist investigating perception, colour, and spatial experience. During his 2017 residency, Loke created abstract works that created immersive chromatic environments.', images: ['justin.png'], video: '' },
		{ slug: 'kate-bae', name: 'Kate Bae', year: '2017', country: 'South Korea', desc: 'South Korean artist working with textile, embroidery, and craft as feminist practice. During her 2017 residency, Bae’s meticulously sewn works reclaimed women’s domestic labour as a powerful site of artistic expression.', images: ['Kate-Bae-pdf.jpg', 'Kate_Bae.jpg'], video: '' },
		{ slug: 'reza-zefanya-mulia', name: 'Reza Zefanya Mulia', year: '2017', country: 'Indonesia', desc: 'Indonesian painter whose figurative works examine youth culture, identity, and social media. During his 2017 residency, Mulia’s vibrant, candid portraits captured the aspirations and anxieties of Indonesia’s digital generation.', images: ['Reza-Zefanya-Mulia-pdf.jpg'], video: '' },
		{ slug: 'catherine-ellis', name: 'Catherine Ellis', year: '2018', country: 'USA', desc: 'American artist working across photography, video, and social documentary. During her 2018 residency at TENTACLES, Ellis focused on communities on the margins in Bangkok.', images: ['Catherine-Ellis-Profile-Image.png'], video: '' },
		{ slug: 'joned', name: 'Joned', year: '2018', country: 'Thailand', desc: 'Bangkok-based artist working across street art, painting, and public intervention. During his 2018 residency at TENTACLES, Joned created bold graphic works drawing on Thai pop culture, political satire, and urban subcultures.', images: ['joned.png'], video: '' },
		{ slug: 'karl-ingar-roys', name: 'Karl Ingar Røys', year: '2018', country: 'Norway', desc: 'Norwegian artist whose work bridges performance, sculpture, and ecological thinking. During his 2018 residency, Røys created durational performances and installation works engaging with natural cycles and environmental degradation.', images: ['ingar.png'], video: '' },
		{ slug: 'linh-phuong-nguyen', name: 'Linh Phuong Nguyen', year: '2018', country: 'Vietnam', desc: 'Vietnamese artist exploring the poetics of everyday objects through installation and drawing. During her 2018 residency, Nguyen transformed mundane materials into delicate, contemplative works.', images: ['Nguyen.png'], video: '' },
		{ slug: 'liuboda', name: 'LiuBoda', year: '2018', country: 'China', desc: 'Chinese painter working with abstraction, gesture, and the language of mark-making. During his 2018 residency at TENTACLES, Liu created large-scale canvases channeling energy and emotion through spontaneous brushwork.', images: ['liuboda-1.jpg', 'liuboda-2.jpg'], video: '' },
		{ slug: 'rar-edition', name: 'RAR Edition', year: '2018', country: 'Thailand', desc: 'A collaborative project exploring artist books, zines, and printed matter as artistic medium. RAR Edition brought together writers, designers, and artists during their 2018 residency to produce experimental publications.', images: [], video: '' },
		{ slug: 'sunya', name: 'Sunya', year: '2018', country: 'Thailand', desc: 'Thailand-based artist whose work investigates spiritual ecology and material transformation. During her 2018 residency, Sunya created ritualistic installations meditating on impermanence and the cycle of life.', images: [], video: '' },
		{ slug: 'yeon-jeong', name: 'Yeon Jeong', year: '2018', country: 'South Korea', desc: 'South Korean artist whose work investigates femininity, memory, and material culture. During her 2018 residency, Jeong created intimate installations weaving personal and collective histories through textile, drawing, and found objects.', images: ['yeon.png'], video: '' },
		{ slug: 'ho-rui-an', name: 'Ho Rui An', year: '2019', country: 'Singapore', desc: 'Singaporean artist working across film, drawing, and performance to examine image economies. During his 2019 residency, Ho’s critically engaged practice unpacked the geopolitics of visual culture.', images: ['horuian.png'], video: '' },
];
